version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
